import {
  Content,
  MainTitle,
  SubTitle,
  Title,
  UpdatedAt,
  Wrapper,
} from './styles';

export default function PrivacyPolicyPage() {
  return (
    <Wrapper>
      <MainTitle>Privacy Policy</MainTitle>
      <UpdatedAt>Last updated July 15, 2023</UpdatedAt>
      <div>
        <Content>
          {`VisionLab, Inc ("us", "we", or "our") operates the
          https://avatarist.ai/ website and Creatorhub mobile applications (the
          "Service"). This page informs you of our policies regarding the
          collection, use, and disclosure of personal data when you use our
          Service and the choices you have associated with that data. We use
          your data to provide and improve the Service. By using the Service,
          you agree to the collection and use of information in accordance with
          this policy. Unless otherwise defined in this Privacy Policy, terms
          used in this Privacy Policy have the same meanings as in our Terms of
          Use, accessible from https://avatarist.ai//terms/`}
        </Content>

        <Title>Definitions</Title>
        <Content>
          Service: The service is the https://avatarist.ai/ website and the
          mobile applications operated by VisionLab, Inc
          <br />
          <br />
          Personal Data: Personal Data means any data that identifies or that
          can be used to identify an individual.
          <br />
          <br />
          For the purposes of the California Consumer Privacy Act (CCPA),
          Personal Data means any information that identifies, relates to,
          describes, or is capable of being associated with, or could reasonably
          be linked, directly or indirectly, with a particular Consumer or
          household.
          <br />
          <br />
          Usage Data: Usage Data is data collected automatically either
          generated by the use of the Service or from the Service infrastructure
          itself (for example, the duration of a page visit).
          <br />
          <br />
          Cookies: Cookies are files with a small amount of data stored on your
          device (computer or mobile device).
          <br />
          <br />
          Data Controller: Data Controller means the natural or legal person who
          (either alone or jointly or in common with other persons) determines
          the purposes for which and the manner in which any personal
          information are, or are to be, processed.
          <br />
          <br />
          For the purpose of this Privacy Policy, we are a Data Controller of
          your Personal Data.
          <br />
          <br />
          Data Processors (or Service Providers): Data Processor (or Service
          Provider) means any natural or legal person who processes the data on
          behalf of the Data Controller. We may use the services of various
          Service Providers in order to process your data more effectively.
          <br />
          <br />
          Data Subject (or User or Consumer): Data Subject is any individual who
          is using our Service and is the subject of Personal Data.
        </Content>

        <Title>Information Collection and Use</Title>
        <Content>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
          <br />
          <br />
          {/* subtitle */}
          <SubTitle>Types of Data Collected</SubTitle>
          <br />
          <br />
          While using our Service, we may ask you to provide us with certain
          Personal Data, which may include:
          <ul>
            <li>Email address</li>
            <li>First name and last name</li>
            <li>Address, State, Province, ZIP/Postal code, City</li>
            <li>Cookies and Usage Data</li>
            <li>Photographs and graphics</li>
            <li>
              Record of correspondence when you contact us through customer
              support.
            </li>
          </ul>
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials, and other information that may be
          of interest to you. You may opt-out of receiving any, or all, of these
          communications from us by following the unsubscribe link or
          instructions provided in any email we send.
          <br />
          <br />
          {/* subtitle */}
          <SubTitle>Usage Data</SubTitle>
          <br />
          <br />
          {`We may collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device ("Usage Data").`}
          <br />
          <br />
          {`This Usage Data may include information such as your computer's
          Internet Protocol address (i.e., IP address), browser type, browser
          version, the pages of our Service that you visit, the time and date of
          your visit, the time spent on those pages, unique device identifiers
          and other diagnostic data.`}
          <br />
          <br />
          When you access the Service with a mobile device, this Usage Data may
          include information such as the type of mobile device you use, the IP
          address of your mobile device, your mobile operating system, the type
          of mobile Internet browser you use, unique device identifiers and
          other diagnostic data.
          <br />
          <br />
          {/* subtitle */}
          <SubTitle> Tracking & Cookies Data</SubTitle>
          <br />
          <br />
          We use cookies and similar tracking technologies to track the activity
          on our Service and hold certain information.
          <br />
          <br />
          Cookies are files with a small amount of data which may include an
          anonymous unique identifier. Cookies are sent to your browser from a
          website and stored on your device. Tracking technologies also used are
          beacons, tags, and scripts to collect and track information and to
          improve and analyze our Service.
          <br />
          <br />
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
          <br />
          <br />
          Examples of Cookies we use:
          <ul>
            <li>
              Session Cookies. We use Session Cookies to operate our Service.
            </li>
            <li>
              Preference Cookies. We use Preference Cookies to remember your
              preferences and various settings.
            </li>
            <li>
              Security Cookies. We use Security Cookies for security purposes.
            </li>
            <li>
              Advertising Cookies. Advertising Cookies serve you with
              advertisements that may be relevant to you and your interests.
            </li>
          </ul>
          {/* subtitle */}
          <SubTitle> Photographs and Graphics</SubTitle>
          <br />
          <br />
          We use your photographs and graphics to provide the Service.
          <br />
          <br />
          The photographs and graphics that you upload to our website are always
          private, and they may never ever be public without your consent, that
          is unless you are opt-in to make them public. If you ever elect to
          make your photographs and graphics that you upload to our website to
          be public, we may use them for editorial purposes in line with our
          Terms of Use, accessible from{' '}
          <a href={'https://avatarist.ai//terms/'}>
            https://avatarist.ai//terms/
          </a>
          , for example, your photograph may appear on our website as a featured
          image. You may always make your public photographs and graphics
          private and we will cease to use them for any purpose other than
          providing the Service.
          <br />
          <br />
          Remember that you can delete your Personal Data directly within your
          Account Settings section. If you are unable to perform these actions
          yourself, please contact us to assist you.
          <br />
          <br />
          {/* subtitle */}
          <SubTitle>
            Information from Third-Party Social Media Services
          </SubTitle>
          <br />
          <br />
          VisionLab, Inc. allows you to create an account and log in to use the
          Service through third-party social media services, such as Google,
          Facebook, and Twitter.
          <br />
          <br />
          {`If you decide to register through or otherwise grant us access to a
          third-party social media service, we may collect Personal Data that is
          already associated with your third-party social media service's
          account, such as your name, your email address associated with that
          account.`}
          <br />
          <br />
          {`You may also have the option of sharing additional information with us
          through your third-party social media service's account. If you choose
          to provide such information and Personal Data, during registration or
          otherwise, you are giving us permission to use, share, and store it in
          a manner consistent with this Privacy Policy.`}
          <br />
          <br />
          If you choose to use any third-party social media sites, services, or
          features in connection with the Service, such features and any
          information transferred to us will be governed by the privacy policies
          of the respective third-party social media services. We have no
          control over and assume no responsibility for the content, privacy
          policies, or practices of any third-party sites or services.
        </Content>

        <Title>Use of Data</Title>
        <Content>
          VisionLab, Inc uses the collected data for various purposes:
          <ul>
            <li>To provide and maintain our Service</li>
            <li>To notify you about changes to our Service</li>
            <li>
              To allow you to participate in interactive features of our Service
              when you choose to do so
            </li>
            <li>To process payments</li>
            <li>To provide customer support</li>
            <li>
              To gather analysis or valuable information so that we can improve
              our Service
            </li>
            <li>To monitor the usage of our Service</li>
            <li>To detect, prevent and address technical issues</li>
            <li>
              To provide you with news, special offers, and general information
              about other goods, services, and events that we offer that are
              similar to those that you have already purchased or enquired about
              unless you have opted not to receive such information
            </li>
          </ul>
        </Content>
      </div>
    </Wrapper>
  );
}
